package meet.myo.domain.adopt.notice;

public enum City {
    SEOUL, SEJONG, BUSAN, DAEGU, INCHEON, GWANGJU, ULSAN, DAEJEON,
    GYEONGGI, GANGWON, CHUNGCHEONG_BUK, CHUNGCHEONG_NAM, JEOLLA_BUK, JEOLLA_NAM,
    GYEONGSANG_BUK, GYEONGSANG_NAM, JEJU
}
