spring:
  config:
    import:
      - classpath:/config/secret.yml

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/myomeet?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: myo9876!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        show_sql: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace


springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    defaultModelsExpandDepth: -1


jwt:
    access-token-validity-time: 180000 # 3분
    refresh-token-validity-time: 60480000 # 1008분

