spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:myomeet
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

jwt:
    access-token-validity-time: 180000 # 3분
    refresh-token-validity-time: 60480000 # 1008분



